# Generated by Django 5.2.1 on 2025-05-24 00:41

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('mahasiswa', 'Mahasiswa'), ('dosen', 'Dosen'), ('prodi', 'Program Studi'), ('fakultas', 'Fakultas')], default='mahasiswa', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nidn', models.CharField(max_length=20, unique=True, verbose_name='NIDN')),
                ('nip', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='NIP')),
                ('jabatan_akademik', models.CharField(blank=True, choices=[('Asisten Ahli', 'Asisten Ahli'), ('Lektor', 'Lektor'), ('Lektor Kepala', 'Lektor Kepala'), ('Profesor', 'Profesor')], max_length=50)),
                ('pendidikan_terakhir', models.CharField(choices=[('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3')], default='S2', max_length=10)),
                ('bidang_keahlian', models.CharField(blank=True, max_length=100)),
                ('status_kepegawaian', models.CharField(choices=[('PNS', 'PNS'), ('Non-PNS', 'Non-PNS'), ('Kontrak', 'Kontrak')], default='PNS', max_length=20)),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'dosen'}, on_delete=django.db.models.deletion.CASCADE, related_name='dosen_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fakultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('kode', models.CharField(max_length=10, unique=True)),
                ('deskripsi', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dekan', models.OneToOneField(blank=True, limit_choices_to={'user_type': 'fakultas'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fakultas_dipimpin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Fakultas',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('prodi', 'Program Studi'), ('fakultas', 'Fakultas'), ('public', 'Public')], default='private', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramStudi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('kode', models.CharField(max_length=10, unique=True)),
                ('jenjang', models.CharField(choices=[('D3', 'Diploma 3'), ('S1', 'Sarjana'), ('S2', 'Magister'), ('S3', 'Doktor')], default='S1', max_length=20)),
                ('akreditasi', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('Baik Sekali', 'Baik Sekali'), ('Baik', 'Baik')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fakultas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_studi', to='accounts.fakultas')),
                ('kaprodi', models.OneToOneField(blank=True, limit_choices_to={'user_type': 'prodi'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prodi_dipimpin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Program Studi',
            },
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=20, unique=True, verbose_name='NIM')),
                ('angkatan', models.CharField(max_length=4)),
                ('semester', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('Aktif', 'Aktif'), ('Cuti', 'Cuti'), ('Non-Aktif', 'Non-Aktif'), ('Lulus', 'Lulus'), ('DO', 'Drop Out')], default='Aktif', max_length=20)),
                ('ipk', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('tanggal_masuk', models.DateField()),
                ('dosen_wali', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mahasiswa_bimbingan', to='accounts.dosen')),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'mahasiswa'}, on_delete=django.db.models.deletion.CASCADE, related_name='mahasiswa_profile', to=settings.AUTH_USER_MODEL)),
                ('program_studi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahasiswa', to='accounts.programstudi')),
            ],
        ),
        migrations.AddField(
            model_name='dosen',
            name='program_studi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosen', to='accounts.programstudi'),
        ),
        migrations.CreateModel(
            name='StaffFakultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan', models.CharField(blank=True, max_length=50)),
                ('fakultas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='accounts.fakultas')),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'fakultas'}, on_delete=django.db.models.deletion.CASCADE, related_name='staff_fakultas_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffProdi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan', models.CharField(blank=True, max_length=50)),
                ('program_studi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='accounts.programstudi')),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'prodi'}, on_delete=django.db.models.deletion.CASCADE, related_name='staff_prodi_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
