# Generated by Django 5.2.1 on 2025-06-22 11:53

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisLayanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_layanan', models.CharField(max_length=255)),
                ('deskripsi_layanan', models.TextField(blank=True, null=True)),
                ('prasyarat_layanan', models.TextField(blank=True, null=True)),
                ('konfigurasi_field', models.JSONField(blank=True, null=True)),
                ('template_surat', models.CharField(blank=True, help_text='Path ke template surat, contoh: surat/cuti_akademik.html', max_length=255, null=True)),
                ('penandatangan_otomatis', models.JSONField(blank=True, default=list, help_text="Daftar penandatangan otomatis dalam format JSON. Contoh: [{'role': 'Ketua Prodi', 'user_type': 'ketua_prodi', 'order': 1}]", null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jurusan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_jurusan', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Aktif', 'Aktif'), ('NonAktif', 'NonAktif')], default='Aktif', max_length=10)),
                ('kode_surat', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Nama Jurusan',
                'verbose_name_plural': 'Nama Jurusan',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nama Lengkap')),
                ('user_type', models.CharField(choices=[('super_admin', 'SUPER ADMIN'), ('dekan_fakultas', 'USER DEKAN'), ('pejabat_jurusan', 'USER PEJABAT JURUSAN'), ('ketua_prodi', 'USER KETUA PRODI'), ('staff_fakultas', 'USER STAFF FAKULTAS'), ('staff_prodi', 'USER STAFF PRODI'), ('dosen', 'USER DOSEN'), ('mahasiswa', 'USER MAHASISWA')], default='mahasiswa', max_length=20)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/%Y/%m/')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tempat_lahir', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'All User',
                'verbose_name_plural': 'All User',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Fakultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('kode', models.CharField(max_length=10, unique=True)),
                ('dekan', models.OneToOneField(blank=True, limit_choices_to={'user_type': 'dekan_fakultas'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fakultas_dipimpin', to=settings.AUTH_USER_MODEL)),
                ('wakil_dekan_akademik', models.ForeignKey(blank=True, limit_choices_to={'user_type__in': ['dekan_fakultas']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fakultas_wd_akademik', to=settings.AUTH_USER_MODEL, verbose_name='Wakil Dekan Bidang Akademik')),
                ('wakil_dekan_kemahasiswaan_alumni', models.ForeignKey(blank=True, limit_choices_to={'user_type__in': ['dekan_fakultas']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fakultas_wd_kemahasiswaan_alumni', to=settings.AUTH_USER_MODEL, verbose_name='Wakil Dekan Bidang Kemahasiswaan dan Alumni')),
                ('wakil_dekan_kerjasama', models.ForeignKey(blank=True, limit_choices_to={'user_type__in': ['dekan_fakultas']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fakultas_wd_kerjasama', to=settings.AUTH_USER_MODEL, verbose_name='Wakil Dekan Bidang Kerjasama')),
                ('wakil_dekan_umum_keuangan', models.ForeignKey(blank=True, limit_choices_to={'user_type__in': ['dekan_fakultas']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fakultas_wd_umum_keuangan', to=settings.AUTH_USER_MODEL, verbose_name='Wakil Dekan Bidang Umum dan Keuangan')),
            ],
            options={
                'verbose_name': 'Nama Fakultas',
                'verbose_name_plural': 'Nama Fakultas',
            },
        ),
        migrations.CreateModel(
            name='Layanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Waiting', 'Menunggu Diproses'), ('Processing', 'Sedang Diproses'), ('Completed', 'Selesai'), ('Rejected', 'Ditolak')], default='Waiting', max_length=50)),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('isi_permohonan', models.TextField()),
                ('file_permohonan', models.FileField(blank=True, null=True, upload_to='layanan/permohonan/')),
                ('data_tambahan', models.JSONField(blank=True, null=True)),
                ('hasil_proses', models.TextField(blank=True, null=True)),
                ('file_hasil', models.FileField(blank=True, null=True, upload_to='layanan/hasil/')),
                ('link_hasil', models.URLField(blank=True, null=True)),
                ('admin_pemroses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layanan_admin_pemroses', to=settings.AUTH_USER_MODEL)),
                ('jenis_layanan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layanan_list', to='accounts.jenislayanan')),
                ('mahasiswa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layanan_mahasiswa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataTambahanFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_field', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='layanan/file_tambahan/')),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
                ('layanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_tambahan', to='accounts.layanan')),
            ],
        ),
        migrations.CreateModel(
            name='NomorSurat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('nomor', models.IntegerField()),
                ('kode', models.CharField(default='UN36.7.1', max_length=20)),
                ('jenis', models.CharField(default='KM', max_length=10)),
                ('tahun', models.CharField(max_length=4)),
                ('perihal', models.TextField()),
                ('tujuan', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('aktif', 'Aktif'), ('nonaktif', 'Nonaktif'), ('dihapus', 'Dihapus')], default='draft', max_length=10)),
                ('admin_nomor_surat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomor_surat_created', to=settings.AUTH_USER_MODEL)),
                ('jurusan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nomor_surat', to='accounts.jurusan')),
            ],
            options={
                'ordering': ['-tahun', '-nomor'],
            },
        ),
        migrations.AddField(
            model_name='layanan',
            name='nomor_surat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layanan_nomor_surat', to='accounts.nomorsurat'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('prodi', 'Program Studi'), ('fakultas', 'Fakultas'), ('public', 'Public')], default='private', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PejabatJurusan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan', models.CharField(choices=[('Ketua', 'Ketua'), ('Sekretaris', 'Sekretaris')], max_length=15)),
                ('tgl_mulai', models.DateField()),
                ('tgl_selesai', models.DateField()),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('plt', models.BooleanField(blank=True, null=True)),
                ('jurusan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pejabat_jurusan_rel', to='accounts.jurusan')),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'pejabat_jurusan'}, on_delete=django.db.models.deletion.CASCADE, related_name='pejabat_jurusan_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Pejabat Jurusan',
                'verbose_name_plural': 'User Pejabat Jurusan',
            },
        ),
        migrations.CreateModel(
            name='ProgramStudi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('kode', models.CharField(max_length=10, unique=True)),
                ('gelar', models.CharField(blank=True, max_length=20, null=True)),
                ('jenjang', models.CharField(choices=[('D3', 'Diploma 3'), ('S1', 'Sarjana'), ('S2', 'Magister'), ('S3', 'Doktor')], default='S1', max_length=20)),
                ('akreditasi', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('Baik Sekali', 'Baik Sekali'), ('Baik', 'Baik')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fakultas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_studi', to='accounts.fakultas')),
                ('jurusan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_studi', to='accounts.jurusan')),
                ('kaprodi', models.OneToOneField(blank=True, limit_choices_to={'user_type': 'ketua_prodi'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prodi_dipimpin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'List Program Studi',
            },
        ),
        migrations.AddField(
            model_name='nomorsurat',
            name='program_studi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nomor_surat', to='accounts.programstudi'),
        ),
        migrations.AddField(
            model_name='layanan',
            name='program_studi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layanan_list', to='accounts.programstudi'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Judul')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('content', models.TextField(verbose_name='Konten')),
                ('excerpt', models.TextField(help_text='Ringkasan singkat artikel (max 300 karakter)', max_length=300, verbose_name='Ringkasan')),
                ('category', models.CharField(choices=[('akademik', 'Akademik'), ('event', 'Event'), ('prestasi', 'Prestasi'), ('kerjasama', 'Kerjasama'), ('workshop', 'Workshop'), ('penelitian', 'Penelitian'), ('pengumuman', 'Pengumuman'), ('beasiswa', 'Beasiswa'), ('news', 'News')], default='news', max_length=20)),
                ('tags', models.CharField(blank=True, help_text='Pisahkan tag dengan koma', max_length=255)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='articles/images/%Y/%m/', verbose_name='Gambar Utama')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False, verbose_name='Tampilkan di Halaman Utama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, help_text='Judul untuk SEO (opsional)', max_length=100)),
                ('meta_description', models.TextField(blank=True, help_text='Deskripsi untuk SEO (opsional)')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
                ('related_prodi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='accounts.programstudi', verbose_name='Program Studi Terkait')),
            ],
            options={
                'verbose_name': 'Artikel',
                'verbose_name_plural': 'Artikel',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserDosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='NIP')),
                ('jabatan_akademik', models.CharField(blank=True, choices=[('Asisten Ahli', 'Asisten Ahli'), ('Lektor', 'Lektor'), ('Lektor Kepala', 'Lektor Kepala'), ('Profesor', 'Profesor')], max_length=50)),
                ('pendidikan_terakhir', models.CharField(choices=[('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3')], default='S2', max_length=10)),
                ('bidang_keahlian', models.CharField(blank=True, max_length=100)),
                ('status_kepegawaian', models.CharField(choices=[('PNS', 'PNS'), ('Non-PNS', 'Non-PNS'), ('Kontrak', 'Kontrak')], default='PNS', max_length=20)),
                ('program_studi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosen', to='accounts.programstudi')),
                ('user', models.OneToOneField(limit_choices_to={'user_type__in': ['dosen', 'dekan_fakultas', 'ketua_prodi', 'pejabat_jurusan']}, on_delete=django.db.models.deletion.CASCADE, related_name='dosen_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Dosen',
                'verbose_name_plural': 'User Dosen',
            },
        ),
        migrations.CreateModel(
            name='UserKetuaProdi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode_mulai', models.DateField()),
                ('periode_selesai', models.DateField()),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('plt', models.BooleanField(blank=True, null=True)),
                ('program_studi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ketua_prodi_rel', to='accounts.programstudi')),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'ketua_prodi'}, on_delete=django.db.models.deletion.CASCADE, related_name='ketua_prodi_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Ketua Program Studi',
                'verbose_name_plural': 'User Ketua Program Studi',
            },
        ),
        migrations.CreateModel(
            name='UserMahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='NIM')),
                ('angkatan', models.CharField(max_length=4)),
                ('semester', models.PositiveIntegerField(default=1)),
                ('kelas', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], max_length=10, null=True)),
                ('status', models.CharField(choices=[('Aktif', 'Aktif'), ('Cuti', 'Cuti'), ('Non-Aktif', 'Non-Aktif'), ('Lulus', 'Lulus'), ('DO', 'Drop Out')], default='Aktif', max_length=20)),
                ('ipk', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('tanggal_masuk', models.DateField()),
                ('dosen_wali', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mahasiswa_bimbingan', to='accounts.userdosen')),
                ('program_studi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahasiswa', to='accounts.programstudi')),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'mahasiswa'}, on_delete=django.db.models.deletion.CASCADE, related_name='mahasiswa_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Mahasiswa',
                'verbose_name_plural': 'User Mahasiswa',
                'ordering': ['angkatan', 'kelas', 'nim'],
            },
        ),
        migrations.CreateModel(
            name='SkripsiJudul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_1', models.CharField(max_length=255)),
                ('deskripsi_1', models.TextField()),
                ('judul_2', models.CharField(max_length=255)),
                ('deskripsi_2', models.TextField()),
                ('judul_3', models.CharField(max_length=255)),
                ('deskripsi_3', models.TextField()),
                ('judul_diterima', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Menunggu Review'), ('reviewed_prodi', 'Sudah Direview Prodi'), ('reviewed_fakultas', 'Sudah Direview Fakultas'), ('accepted', 'Diterima'), ('rejected', 'Ditolak'), ('revision', 'Perlu Revisi')], default='pending', max_length=20)),
                ('tanggal_pengajuan', models.DateTimeField(auto_now_add=True)),
                ('tanggal_update', models.DateTimeField(auto_now=True)),
                ('catatan_prodi', models.TextField(blank=True, null=True)),
                ('catatan_fakultas', models.TextField(blank=True, null=True)),
                ('catatan_pembimbing', models.TextField(blank=True, null=True)),
                ('pembimbing_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bimbingan_1', to='accounts.userdosen')),
                ('pembimbing_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bimbingan_2', to='accounts.userdosen')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengajuan_judul', to='accounts.usermahasiswa')),
            ],
            options={
                'verbose_name': 'Pengajuan Judul Skripsi',
                'verbose_name_plural': 'Pengajuan Judul Skripsi',
                'ordering': ['-tanggal_pengajuan'],
            },
        ),
        migrations.CreateModel(
            name='UserStaffFakultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan', models.CharField(blank=True, max_length=50)),
                ('nip', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='NIP')),
                ('fakultas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='accounts.fakultas')),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'staff_fakultas'}, on_delete=django.db.models.deletion.CASCADE, related_name='staff_fakultas_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Staff Fakultas',
                'verbose_name_plural': 'User Staff Fakultas',
            },
        ),
        migrations.CreateModel(
            name='UserStaffProdi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan', models.CharField(blank=True, choices=[('Admin Prodi', 'Admin Prodi'), ('Sekretaris Prodi', 'Sekretaris Prodi')], max_length=50)),
                ('nip', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='NIP')),
                ('program_studi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_prodi', to='accounts.programstudi')),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'staff_prodi'}, on_delete=django.db.models.deletion.CASCADE, related_name='staff_prodi_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Staff Program Studi',
                'verbose_name_plural': 'User Staff Program Studi',
            },
        ),
        migrations.AlterUniqueTogether(
            name='nomorsurat',
            unique_together={('nomor', 'tahun', 'jenis')},
        ),
        migrations.CreateModel(
            name='TandaTanganSurat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urutan', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Belum Ditandatangani'), ('signed', 'Sudah Ditandatangani')], default='pending', max_length=20)),
                ('waktu_tanda_tangan', models.DateTimeField(blank=True, null=True)),
                ('layanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tugas_tanda_tangan', to='accounts.layanan')),
                ('penandatangan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tugas_tanda_tangan_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['layanan', 'urutan'],
                'unique_together': {('layanan', 'penandatangan')},
            },
        ),
    ]
