# Generated by Django 5.2.1 on 2025-05-31 04:08

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jurusan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_jurusan', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Aktif', 'Aktif'), ('NonAktif', 'NonAktif')], default='Aktif', max_length=10)),
                ('kode_surat', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Nama Jurusan',
                'verbose_name_plural': 'Nama Jurusan',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nama Lengkap')),
                ('user_type', models.CharField(choices=[('super_admin', 'SUPER ADMIN'), ('dekan_fakultas', 'USER DEKAN'), ('pejabat_jurusan', 'USER PEJABAT JURUSAN'), ('ketua_prodi', 'USER KETUA PRODI'), ('staff_fakultas', 'USER STAFF FAKULTAS'), ('staff_prodi', 'USER STAFF PRODI'), ('dosen', 'USER DOSEN'), ('mahasiswa', 'USER MAHASISWA')], default='mahasiswa', max_length=20)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/%Y/%m/')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tempat_lahir', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'All User',
                'verbose_name_plural': 'All User',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Fakultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('kode', models.CharField(max_length=10, unique=True)),
                ('dekan', models.OneToOneField(blank=True, limit_choices_to={'user_type': 'dekan_fakultas'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fakultas_dipimpin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nama Fakultas',
                'verbose_name_plural': 'Nama Fakultas',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('prodi', 'Program Studi'), ('fakultas', 'Fakultas'), ('public', 'Public')], default='private', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PejabatJurusan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan', models.CharField(choices=[('Ketua', 'Ketua'), ('Sekretaris', 'Sekretaris')], max_length=15)),
                ('tgl_mulai', models.DateField()),
                ('tgl_selesai', models.DateField()),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('plt', models.BooleanField(blank=True, null=True)),
                ('jurusan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.jurusan')),
                ('pejabat', models.OneToOneField(blank=True, limit_choices_to={'user_type': 'pejabat_jurusan'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pejabat_jurusan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Pejabat Jurusan',
                'verbose_name_plural': 'User Pejabat Jurusan',
            },
        ),
        migrations.CreateModel(
            name='ProgramStudi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('kode', models.CharField(max_length=10, unique=True)),
                ('gelar', models.CharField(blank=True, max_length=20, null=True)),
                ('jenjang', models.CharField(choices=[('D3', 'Diploma 3'), ('S1', 'Sarjana'), ('S2', 'Magister'), ('S3', 'Doktor')], default='S1', max_length=20)),
                ('akreditasi', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('Baik Sekali', 'Baik Sekali'), ('Baik', 'Baik')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fakultas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_studi', to='accounts.fakultas')),
                ('jurusan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_studi', to='accounts.jurusan')),
                ('kaprodi', models.OneToOneField(blank=True, limit_choices_to={'user_type': 'ketua_prodi'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prodi_dipimpin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'List Program Studi',
            },
        ),
        migrations.CreateModel(
            name='UserDosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='NIP')),
                ('jabatan_akademik', models.CharField(blank=True, choices=[('Asisten Ahli', 'Asisten Ahli'), ('Lektor', 'Lektor'), ('Lektor Kepala', 'Lektor Kepala'), ('Profesor', 'Profesor')], max_length=50)),
                ('pendidikan_terakhir', models.CharField(choices=[('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3')], default='S2', max_length=10)),
                ('bidang_keahlian', models.CharField(blank=True, max_length=100)),
                ('status_kepegawaian', models.CharField(choices=[('PNS', 'PNS'), ('Non-PNS', 'Non-PNS'), ('Kontrak', 'Kontrak')], default='PNS', max_length=20)),
                ('program_studi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosen', to='accounts.programstudi')),
                ('user', models.OneToOneField(limit_choices_to={'user_type__in': ['dosen', 'dekan_fakultas', 'ketua_prodi', 'pejabat_jurusan']}, on_delete=django.db.models.deletion.CASCADE, related_name='dosen_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Dosen',
                'verbose_name_plural': 'User Dosen',
            },
        ),
        migrations.CreateModel(
            name='UserKetuaProdi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode_mulai', models.DateField()),
                ('periode_selesai', models.DateField()),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('plt', models.BooleanField(blank=True, null=True)),
                ('program_studi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ketua_prodi_rel', to='accounts.programstudi')),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'ketua_prodi'}, on_delete=django.db.models.deletion.CASCADE, related_name='ketua_prodi_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Ketua Program Studi',
                'verbose_name_plural': 'User Ketua Program Studi',
            },
        ),
        migrations.CreateModel(
            name='UserMahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=20, unique=True, verbose_name='NIM')),
                ('angkatan', models.CharField(max_length=4)),
                ('semester', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('Aktif', 'Aktif'), ('Cuti', 'Cuti'), ('Non-Aktif', 'Non-Aktif'), ('Lulus', 'Lulus'), ('DO', 'Drop Out')], default='Aktif', max_length=20)),
                ('ipk', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('tanggal_masuk', models.DateField()),
                ('dosen_wali', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mahasiswa_bimbingan', to='accounts.userdosen')),
                ('program_studi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahasiswa', to='accounts.programstudi')),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'mahasiswa'}, on_delete=django.db.models.deletion.CASCADE, related_name='mahasiswa_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Mahasiswa',
                'verbose_name_plural': 'User Mahasiswa',
            },
        ),
        migrations.CreateModel(
            name='SkripsiJudul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_1', models.CharField(max_length=255)),
                ('deskripsi_1', models.TextField()),
                ('judul_2', models.CharField(max_length=255)),
                ('deskripsi_2', models.TextField()),
                ('judul_3', models.CharField(max_length=255)),
                ('deskripsi_3', models.TextField()),
                ('judul_diterima', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Menunggu Review'), ('reviewed_prodi', 'Sudah Direview Prodi'), ('reviewed_fakultas', 'Sudah Direview Fakultas'), ('accepted', 'Diterima'), ('rejected', 'Ditolak'), ('revision', 'Perlu Revisi')], default='pending', max_length=20)),
                ('tanggal_pengajuan', models.DateTimeField(auto_now_add=True)),
                ('tanggal_update', models.DateTimeField(auto_now=True)),
                ('catatan_prodi', models.TextField(blank=True, null=True)),
                ('catatan_fakultas', models.TextField(blank=True, null=True)),
                ('catatan_pembimbing', models.TextField(blank=True, null=True)),
                ('pembimbing_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bimbingan_1', to='accounts.userdosen')),
                ('pembimbing_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bimbingan_2', to='accounts.userdosen')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengajuan_judul', to='accounts.usermahasiswa')),
            ],
            options={
                'verbose_name': 'Pengajuan Judul Skripsi',
                'verbose_name_plural': 'Pengajuan Judul Skripsi',
                'ordering': ['-tanggal_pengajuan'],
            },
        ),
        migrations.CreateModel(
            name='UserStaffFakultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan', models.CharField(blank=True, max_length=50)),
                ('nip', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='NIP')),
                ('fakultas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='accounts.fakultas')),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'staff_fakultas'}, on_delete=django.db.models.deletion.CASCADE, related_name='staff_fakultas_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Staff Fakultas',
                'verbose_name_plural': 'User Staff Fakultas',
            },
        ),
        migrations.CreateModel(
            name='UserStaffProdi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan', models.CharField(blank=True, choices=[('Admin Prodi', 'Admin Prodi'), ('Sekretaris Prodi', 'Sekretaris Prodi')], max_length=50)),
                ('nip', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='NIP')),
                ('program_studi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_prodi', to='accounts.programstudi')),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'staff_prodi'}, on_delete=django.db.models.deletion.CASCADE, related_name='staff_prodi_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Staff Program Studi',
                'verbose_name_plural': 'User Staff Program Studi',
            },
        ),
    ]
