# Generated by Django 5.2.1 on 2025-06-22 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tandatangansurat',
            options={'ordering': ['urutan']},
        ),
        migrations.AlterUniqueTogether(
            name='tandatangansurat',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tandatangansurat',
            name='file_tanda_tangan',
            field=models.ImageField(blank=True, null=True, upload_to='ttd/manual/'),
        ),
        migrations.AddField(
            model_name='tandatangansurat',
            name='jabatan_penandatangan',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tandatangansurat',
            name='jenis_tanda_tangan',
            field=models.CharField(choices=[('manual', 'Manual'), ('elektronik', 'Elektronik')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='tandatangansurat',
            name='perihal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tandatangansurat',
            name='surat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='daftar_tanda_tangan', to='accounts.nomorsurat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tandatangansurat',
            name='tanda_tangan_elektronik',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tandatangansurat',
            name='user_penandatangan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanda_tangan_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='layanan',
            name='jenis_layanan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.jenislayanan'),
        ),
        migrations.AlterField(
            model_name='layanan',
            name='program_studi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.programstudi'),
        ),
        migrations.RemoveField(
            model_name='tandatangansurat',
            name='layanan',
        ),
        migrations.RemoveField(
            model_name='tandatangansurat',
            name='penandatangan',
        ),
    ]
