# Generated by Django 5.2.1 on 2025-06-01 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermahasiswa',
            options={'ordering': ['angkatan', 'kelas', 'nim'], 'verbose_name': 'User Mahasiswa', 'verbose_name_plural': 'User Mahasiswa'},
        ),
        migrations.AddField(
            model_name='usermahasiswa',
            name='kelas',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], max_length=10, null=True),
        ),
    ]
