# Generated by Django 5.2.1 on 2025-05-24 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birthDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
