# Generated by Django 5.2.1 on 2025-06-01 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_usermahasiswa_options_usermahasiswa_kelas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pejabatjurusan',
            name='pejabat',
        ),
        migrations.AddField(
            model_name='pejabatjurusan',
            name='user',
            field=models.OneToOneField(default=1, limit_choices_to={'user_type': 'pejabat_jurusan'}, on_delete=django.db.models.deletion.CASCADE, related_name='pejabat_jurusan_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pejabatjurusan',
            name='jurusan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pejabat_jurusan_rel', to='accounts.jurusan'),
        ),
    ]
