# Generated by Django 5.2.1 on 2025-06-23 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_tandatangansurat_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TandaTanganSurat',
            new_name='TandaTangan',
        ),
    ]
