# Generated by Django 5.2.1 on 2025-06-23 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_tandatangansurat_tandatangan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tandatangan',
            options={'ordering': ['urutan'], 'verbose_name': 'Tanda Tangan', 'verbose_name_plural': 'Tanda Tangan'},
        ),
        migrations.RemoveField(
            model_name='tandatangan',
            name='surat',
        ),
        migrations.AddField(
            model_name='tandatangan',
            name='layanan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='daftar_tanda_tangan', to='accounts.layanan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='layanan',
            name='nomor_surat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layanan', to='accounts.nomorsurat'),
        ),
    ]
