# Generated by Django 5.2.1 on 2025-05-24 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_gender_customuser_tempat_lahir'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='birthDate',
            new_name='birth_date',
        ),
    ]
