# Generated by Django 5.2.1 on 2025-06-03 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_pejabatjurusan_pejabat_pejabatjurusan_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermahasiswa',
            name='nim',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='NIM'),
        ),
    ]
