# Generated by Django 5.2.1 on 2025-06-12 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_usermahasiswa_nim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Judul')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('content', models.TextField(verbose_name='Konten')),
                ('excerpt', models.TextField(help_text='Ringkasan singkat artikel (max 300 karakter)', max_length=300, verbose_name='Ringkasan')),
                ('category', models.CharField(choices=[('akademik', 'Akademik'), ('event', 'Event'), ('prestasi', 'Prestasi'), ('kerjasama', 'Kerjasama'), ('workshop', 'Workshop'), ('penelitian', 'Penelitian'), ('pengumuman', 'Pengumuman'), ('beasiswa', 'Beasiswa'), ('news', 'News')], default='news', max_length=20)),
                ('tags', models.CharField(blank=True, help_text='Pisahkan tag dengan koma', max_length=255)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='articles/images/%Y/%m/', verbose_name='Gambar Utama')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False, verbose_name='Tampilkan di Halaman Utama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, help_text='Judul untuk SEO (opsional)', max_length=100)),
                ('meta_description', models.TextField(blank=True, help_text='Deskripsi untuk SEO (opsional)')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
                ('related_prodi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='accounts.programstudi', verbose_name='Program Studi Terkait')),
            ],
            options={
                'verbose_name': 'Artikel',
                'verbose_name_plural': 'Artikel',
                'ordering': ['-created_at'],
            },
        ),
    ]
