# Generated by Django 5.2.1 on 2025-06-23 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_tandatangan_options_remove_tandatangan_surat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tandatangan',
            options={'ordering': ['urutan'], 'verbose_name': 'Tanda Tangan Surat', 'verbose_name_plural': 'Tanda Tangan Surat'},
        ),
        migrations.RemoveField(
            model_name='tandatangan',
            name='layanan',
        ),
        migrations.AddField(
            model_name='tandatangan',
            name='nomor_surat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='daftar_tanda_tangan', to='accounts.nomorsurat'),
            preserve_default=False,
        ),
    ]
