# Generated by Django 5.2.1 on 2025-06-15 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisLayanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_layanan', models.CharField(max_length=255)),
                ('deskripsi_layanan', models.TextField(blank=True, null=True)),
                ('prasyarat_layanan', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NomorSurat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_dibuat', models.DateField(auto_now_add=True)),
                ('tahun', models.CharField(max_length=5)),
                ('nomor', models.IntegerField()),
                ('perihal', models.CharField(max_length=255)),
                ('tujuan', models.CharField(max_length=255)),
                ('admin_nomor_surat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomorsurat_admin', to=settings.AUTH_USER_MODEL)),
                ('jurusan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.jurusan')),
            ],
            options={
                'ordering': ['-tanggal_dibuat'],
                'unique_together': {('tahun', 'nomor')},
            },
        ),
        migrations.CreateModel(
            name='Layanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('isi_permohonan', models.TextField()),
                ('file_permohonan', models.FileField(blank=True, null=True, upload_to='layanan/permohonan/')),
                ('status', models.CharField(choices=[('Waiting', 'Menunggu Diproses'), ('Processing', 'Sedang Diproses'), ('Completed', 'Selesai'), ('Rejected', 'Ditolak')], default='Waiting', max_length=50)),
                ('hasil_proses', models.TextField(blank=True, null=True)),
                ('file_hasil', models.FileField(blank=True, null=True, upload_to='layanan/hasil/')),
                ('link_hasil', models.URLField(blank=True, null=True)),
                ('admin_pemroses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layanan_admin_pemroses', to=settings.AUTH_USER_MODEL)),
                ('jenis_layanan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.jenislayanan')),
                ('mahasiswa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layanan_mahasiswa', to=settings.AUTH_USER_MODEL)),
                ('program_studi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.programstudi')),
                ('nomor_surat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layanan_nomor_surat', to='accounts.nomorsurat')),
            ],
        ),
        migrations.CreateModel(
            name='TandaTanganSurat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan_penandatangan', models.CharField(max_length=255)),
                ('perihal', models.CharField(blank=True, max_length=255, null=True)),
                ('jenis_tanda_tangan', models.CharField(choices=[('manual', 'Manual'), ('elektronik', 'Elektronik')], default='manual', max_length=20)),
                ('file_tanda_tangan', models.ImageField(blank=True, null=True, upload_to='ttd/manual/')),
                ('tanda_tangan_elektronik', models.CharField(blank=True, max_length=255, null=True)),
                ('waktu_tanda_tangan', models.DateTimeField(blank=True, null=True)),
                ('urutan', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Belum Ditandatangani'), ('signed', 'Sudah Ditandatangani')], default='pending', max_length=20)),
                ('surat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daftar_tanda_tangan', to='accounts.nomorsurat')),
                ('user_penandatangan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanda_tangan_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['urutan'],
            },
        ),
    ]
