# Generated by Django 5.2.1 on 2025-05-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'All Users', 'verbose_name_plural': 'All Users'},
        ),
        migrations.AlterModelOptions(
            name='dosen',
            options={'verbose_name': 'Dosen', 'verbose_name_plural': 'Dosen'},
        ),
        migrations.AlterModelOptions(
            name='mahasiswa',
            options={'verbose_name': 'Mahasiswa', 'verbose_name_plural': 'Mahasiswa'},
        ),
        migrations.AlterModelOptions(
            name='stafffakultas',
            options={'verbose_name': 'Staff Fakultas', 'verbose_name_plural': 'Staff Fakultas'},
        ),
        migrations.AlterModelOptions(
            name='staffprodi',
            options={'verbose_name': 'Staff Program Studi', 'verbose_name_plural': 'Staff Program Studi'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('mahasiswa', 'User Mahasiswa'), ('dosen', 'User Dosen'), ('prodi', 'User Program Studi'), ('fakultas', 'User Dekan')], default='mahasiswa', max_length=20),
        ),
        migrations.AlterField(
            model_name='staffprodi',
            name='jabatan',
            field=models.CharField(blank=True, choices=[('ketua_prodi', 'Ketua Program Studi'), ('admin_prodi', 'Admin Prodi')], max_length=50),
        ),
    ]
