# Generated by Django 5.2.1 on 2025-06-23 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_tandatangan_options_remove_tandatangan_layanan_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tandatangan',
            options={'ordering': ['urutan']},
        ),
        migrations.RenameField(
            model_name='tandatangan',
            old_name='nomor_surat',
            new_name='surat',
        ),
        migrations.AlterField(
            model_name='layanan',
            name='nomor_surat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layanan_nomor_surat', to='accounts.nomorsurat'),
        ),
    ]
