# Generated by Django 5.2.1 on 2025-05-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_options_alter_dosen_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('mahasiswa', 'User Mahasiswa'), ('dosen', 'User Dosen'), ('prodi', 'User Program Studi'), ('fakultas', 'User Dekan'), ('super_admin', 'Super Admin')], default='mahasiswa', max_length=20),
        ),
    ]
