# Generated by Django 5.2.1 on 2025-06-16 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_jenislayanan_nomorsurat_layanan_tandatangansurat'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomorsurat',
            name='program_studi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.programstudi'),
        ),
    ]
