# Generated by Django 5.2.1 on 2025-05-24 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_email_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dosen',
            name='nidn',
        ),
    ]
