# Generated by Django 5.2.1 on 2025-06-23 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_tandatangan_options_remove_tandatangan_surat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tandatangan',
            options={'ordering': ['urutan'], 'verbose_name': 'Tanda Tangan', 'verbose_name_plural': 'Tanda Tangan'},
        ),
        migrations.RemoveField(
            model_name='tandatangan',
            name='layanan',
        ),
        migrations.RemoveField(
            model_name='tandatangan',
            name='status',
        ),
    ]
