# Generated by Django 5.2.1 on 2025-06-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_nomorsurat_program_studi'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomorsurat',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('aktif', 'Aktif'), ('nonaktif', 'Nonaktif'), ('dihapus', 'Dihapus')], default='draft', max_length=20),
        ),
    ]
