# Generated by Django 5.2.1 on 2025-05-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_dosen_nidn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jurusan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_jurusan', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Aktif', 'Aktif'), ('NonAktif', 'NonAktif')], default='Aktif', max_length=10)),
                ('kode_surat', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Jurusan',
                'verbose_name_plural': 'Jurusan',
            },
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-created_at'], 'verbose_name': 'All User', 'verbose_name_plural': 'All User'},
        ),
        migrations.AlterModelOptions(
            name='dosen',
            options={'verbose_name': 'User Dosen', 'verbose_name_plural': 'User Dosen'},
        ),
        migrations.AlterModelOptions(
            name='mahasiswa',
            options={'verbose_name': 'User Mahasiswa', 'verbose_name_plural': 'User Mahasiswa'},
        ),
        migrations.AlterModelOptions(
            name='programstudi',
            options={'verbose_name_plural': 'List Program Studi'},
        ),
        migrations.AlterModelOptions(
            name='stafffakultas',
            options={'verbose_name': 'User Fakultas', 'verbose_name_plural': 'User Fakultas'},
        ),
        migrations.AlterModelOptions(
            name='staffprodi',
            options={'verbose_name': 'User Program Studi', 'verbose_name_plural': 'User Program Studi'},
        ),
    ]
