# Generated by Django 5.2.1 on 2025-06-23 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_tandatangan_options_remove_tandatangan_layanan_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tandatangan',
            options={'ordering': ['layanan', 'urutan'], 'verbose_name': 'Tanda Tangan Layanan', 'verbose_name_plural': 'Tanda Tangan Layanan'},
        ),
        migrations.AddField(
            model_name='tandatangan',
            name='layanan',
            field=models.ForeignKey(default=1, help_text='Layanan yang terkait dengan tanda tangan ini.', on_delete=django.db.models.deletion.CASCADE, related_name='daftar_tanda_tangan', to='accounts.layanan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tandatangan',
            name='file_tanda_tangan',
            field=models.ImageField(blank=True, help_text='File gambar untuk tanda tangan manual.', null=True, upload_to='ttd/manual/'),
        ),
        migrations.AlterField(
            model_name='tandatangan',
            name='jabatan_penandatangan',
            field=models.CharField(help_text='Jabatan penandatangan (misal: Dekan, Ketua Prodi, Staf Admin).', max_length=255),
        ),
        migrations.AlterField(
            model_name='tandatangan',
            name='jenis_tanda_tangan',
            field=models.CharField(choices=[('manual', 'Manual'), ('elektronik', 'Elektronik')], default='manual', help_text='Jenis tanda tangan: manual (gambar) atau elektronik (data).', max_length=20),
        ),
        migrations.AlterField(
            model_name='tandatangan',
            name='perihal',
            field=models.CharField(blank=True, help_text='Konteks spesifik tanda tangan ini, jika berbeda dari perihal layanan.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tandatangan',
            name='tanda_tangan_elektronik',
            field=models.CharField(blank=True, help_text='Data string untuk tanda tangan elektronik (hash, token, dll.).', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tandatangan',
            name='urutan',
            field=models.PositiveIntegerField(default=1, help_text='Urutan tanda tangan dalam alur persetujuan layanan.'),
        ),
        migrations.AlterField(
            model_name='tandatangan',
            name='user_penandatangan',
            field=models.ForeignKey(blank=True, help_text='Akun pengguna yang melakukan tanda tangan.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanda_tangan_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tandatangan',
            name='waktu_tanda_tangan',
            field=models.DateTimeField(blank=True, help_text='Tanggal dan waktu tanda tangan ini dilakukan.', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='tandatangan',
            unique_together={('layanan', 'urutan')},
        ),
        migrations.AddIndex(
            model_name='tandatangan',
            index=models.Index(fields=['layanan', 'urutan'], name='accounts_ta_layanan_a050f0_idx'),
        ),
        migrations.AddIndex(
            model_name='tandatangan',
            index=models.Index(fields=['jenis_tanda_tangan'], name='accounts_ta_jenis_t_16246e_idx'),
        ),
        migrations.AddIndex(
            model_name='tandatangan',
            index=models.Index(fields=['jabatan_penandatangan'], name='accounts_ta_jabatan_36babb_idx'),
        ),
    ]
