# Generated by Django 5.2.1 on 2025-06-17 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_nomorsurat_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nomorsurat',
            options={'ordering': ['-tahun', '-nomor']},
        ),
        migrations.AlterUniqueTogether(
            name='nomorsurat',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='nomorsurat',
            name='jenis',
            field=models.CharField(default='KM', max_length=10),
        ),
        migrations.AddField(
            model_name='nomorsurat',
            name='kode',
            field=models.CharField(default='UN36.7.1', max_length=20),
        ),
        migrations.AlterField(
            model_name='nomorsurat',
            name='admin_nomor_surat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomor_surat_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nomorsurat',
            name='jurusan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nomor_surat', to='accounts.jurusan'),
        ),
        migrations.AlterField(
            model_name='nomorsurat',
            name='perihal',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='nomorsurat',
            name='program_studi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nomor_surat', to='accounts.programstudi'),
        ),
        migrations.AlterField(
            model_name='nomorsurat',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('aktif', 'Aktif'), ('nonaktif', 'Nonaktif'), ('dihapus', 'Dihapus')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='nomorsurat',
            name='tahun',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='nomorsurat',
            name='tanggal_dibuat',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='nomorsurat',
            name='tujuan',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='nomorsurat',
            unique_together={('nomor', 'tahun', 'jenis')},
        ),
    ]
