# Generated by Django 5.2.1 on 2025-05-24 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_jurusan_alter_customuser_options_alter_dosen_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JurusanPejabat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan', models.CharField(choices=[('Ketua', 'Ketua'), ('Sekretaris', 'Sekretaris')], max_length=15)),
                ('tgl_mulai', models.DateField()),
                ('tgl_selesai', models.DateField()),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('plt', models.BooleanField(blank=True, null=True)),
                ('jurusan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.jurusan')),
                ('pejabat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
