# Generated by Django 5.2.1 on 2025-06-18 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_nomorsurat_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='layanan',
            name='data_tambahan',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
