# Generated by Django 5.2.1 on 2025-06-23 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_tandatangan_options_tandatangan_layanan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tandatangan',
            name='file_tanda_tangan',
            field=models.ImageField(blank=True, null=True, upload_to='ttd/manual/'),
        ),
        migrations.AlterField(
            model_name='tandatangan',
            name='jabatan_penandatangan',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tandatangan',
            name='jenis_tanda_tangan',
            field=models.CharField(choices=[('manual', 'Manual'), ('elektronik', 'Elektronik')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='tandatangan',
            name='layanan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daftar_tanda_tangan', to='accounts.layanan'),
        ),
        migrations.AlterField(
            model_name='tandatangan',
            name='perihal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tandatangan',
            name='tanda_tangan_elektronik',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tandatangan',
            name='urutan',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tandatangan',
            name='user_penandatangan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanda_tangan_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tandatangan',
            name='waktu_tanda_tangan',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
