# Generated by Django 5.2.1 on 2025-06-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_tandatangan_file_tanda_tangan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tandatangan',
            name='status',
            field=models.CharField(choices=[('pending', 'Belum Ditandatangani'), ('signed', 'Sudah Ditandatangani')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='tandatangan',
            name='tanda_tangan_elektronik',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tandatangan',
            name='waktu_tanda_tangan',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
