# Generated by Django 5.2.1 on 2025-05-24 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_jurusanpejabat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('mahasiswa', 'User Mahasiswa'), ('dosen', 'User Dosen'), ('prodi', 'User Program Studi'), ('fakultas', 'User Dekan'), ('super_admin', 'Super Admin'), ('jurusan', 'User Jurusan')], default='mahasiswa', max_length=20),
        ),
        migrations.AlterField(
            model_name='jurusanpejabat',
            name='pejabat',
            field=models.OneToOneField(blank=True, limit_choices_to={'user_type': 'jurusan'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pejabat_jurusan', to=settings.AUTH_USER_MODEL),
        ),
    ]
