# Generated by Django 5.2.1 on 2025-06-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_layanan_data_tambahan'),
    ]

    operations = [
        migrations.AddField(
            model_name='jenislayanan',
            name='konfigurasi_field',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
