# Generated by Django 5.2.1 on 2025-05-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customuser_user_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jurusan',
            options={'verbose_name': 'Nama Jurusan', 'verbose_name_plural': 'Nama Jurusan'},
        ),
        migrations.AlterModelOptions(
            name='jurusanpejabat',
            options={'verbose_name': 'User Pejabat Jurusan', 'verbose_name_plural': 'User Pejabat Jurusan'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nama Lengkap'),
        ),
    ]
