# Generated by Django 5.2.1 on 2025-06-18 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_jenislayanan_konfigurasi_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTambahanFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_field', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='layanan/file_tambahan/')),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
                ('layanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_tambahan', to='accounts.layanan')),
            ],
        ),
    ]
