# Generated by Django 5.2.1 on 2025-06-21 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_datatambahanfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='jenislayanan',
            name='template_surat',
            field=models.CharField(blank=True, help_text='Path ke template surat, contoh: surat/cuti_akademik.html', max_length=255, null=True),
        ),
    ]
