# Generated by Django 5.2.1 on 2025-05-24 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_jurusan_options_alter_jurusanpejabat_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fakultas',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='fakultas',
            name='deskripsi',
        ),
    ]
