# Generated by Django 5.2.1 on 2025-06-22 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_jenislayanan_template_surat'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakultas',
            name='wakil_dekan_akademik',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type__in': ['dosen', 'dekan_fakultas', 'pejabat_jurusan']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fakultas_wd_akademik', to=settings.AUTH_USER_MODEL, verbose_name='Wakil Dekan Bidang Akademik'),
        ),
        migrations.AddField(
            model_name='fakultas',
            name='wakil_dekan_kemahasiswaan_alumni',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type__in': ['dosen', 'dekan_fakultas', 'pejabat_jurusan']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fakultas_wd_kemahasiswaan_alumni', to=settings.AUTH_USER_MODEL, verbose_name='Wakil Dekan Bidang Kemahasiswaan dan Alumni'),
        ),
        migrations.AddField(
            model_name='fakultas',
            name='wakil_dekan_kerjasama',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type__in': ['dosen', 'dekan_fakultas', 'pejabat_jurusan']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fakultas_wd_kerjasama', to=settings.AUTH_USER_MODEL, verbose_name='Wakil Dekan Bidang Kerjasama'),
        ),
        migrations.AddField(
            model_name='fakultas',
            name='wakil_dekan_umum_keuangan',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type__in': ['dosen', 'dekan_fakultas', 'pejabat_jurusan']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fakultas_wd_umum_keuangan', to=settings.AUTH_USER_MODEL, verbose_name='Wakil Dekan Bidang Umum dan Keuangan'),
        ),
    ]
