# Generated by Django 5.2.1 on 2025-05-24 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_fakultas_created_at_remove_fakultas_deskripsi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fakultas',
            options={'verbose_name_plural': 'Nama Fakultas'},
        ),
        migrations.AddField(
            model_name='programstudi',
            name='gelar',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='programstudi',
            name='jurusan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='program_studi', to='accounts.jurusan'),
            preserve_default=False,
        ),
    ]
