# Generated by Django 5.2.1 on 2025-05-24 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_fakultas_options_programstudi_gelar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('mahasiswa', 'USER MAHASISWA'), ('dosen', 'USER DOSEN'), ('prodi', 'USER KETUA PRODI'), ('fakultas', 'USER DEKAN'), ('super_admin', 'SUPER ADMIN'), ('jurusan', 'USER PEJABAT JURUSAN'), ('staff_fakultas', 'USER STAFF FAKULTAS'), ('staff_prodi', 'USER STAFF PRODI')], default='mahasiswa', max_length=20),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type__in': ['dosen', 'fakultas', 'prodi']}, on_delete=django.db.models.deletion.CASCADE, related_name='dosen_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stafffakultas',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type': 'staff_fakultas'}, on_delete=django.db.models.deletion.CASCADE, related_name='staff_fakultas_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
