# Generated by Django 5.2.1 on 2025-06-22 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_fakultas_wakil_dekan_akademik_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrukturPenandatangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe_penandatangan', models.CharField(choices=[('DEKAN', 'Dekan'), ('WD_AKADEMIK', 'Wakil Dekan Bidang Akademik'), ('WD_UMUM_KEUANGAN', 'Wakil Dekan Bidang Umum & Keuangan'), ('WD_KEMAHASISWAAN_ALUMNI', 'Wakil Dekan Bidang Kemahasiswaan & Alumni'), ('WD_KERJASAMA', 'Wakil Dekan Bidang Kerjasama'), ('PEJABAT_JURUSAN', 'Pejabat Jurusan'), ('KETUA_PRODI', 'Ketua Program Studi (dari Mahasiswa)'), ('DOSEN_WALI', 'Dosen Wali (PA)')], max_length=50, verbose_name='Peran Penandatangan')),
                ('jabatan_tercetak', models.TextField(help_text='Contoh: Wakil Dekan,<br>Bidang Kemahasiswaan dan Alumni', verbose_name='Jabatan yang Ditampilkan di Surat')),
                ('urutan', models.PositiveIntegerField(default=1, help_text='Urutan tanda tangan pada surat (1, 2, 3, ...)')),
                ('jenis_layanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='struktur_penandatangan', to='accounts.jenislayanan')),
            ],
            options={
                'verbose_name': 'Struktur Penandatangan',
                'verbose_name_plural': 'Struktur Penandatangan',
                'ordering': ['jenis_layanan', 'urutan'],
                'unique_together': {('jenis_layanan', 'urutan')},
            },
        ),
    ]
