# Generated by Django 5.2.1 on 2025-05-24 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_customuser_user_type_alter_dosen_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dosen',
            new_name='UserDosen',
        ),
        migrations.RenameModel(
            old_name='StaffFakultas',
            new_name='UserFakultas',
        ),
        migrations.RenameModel(
            old_name='Mahasiswa',
            new_name='UserMahasiswa',
        ),
        migrations.RenameModel(
            old_name='StaffProdi',
            new_name='UserProdi',
        ),
    ]
