# Generated by Django 5.2.1 on 2025-05-25 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_rename_dosen_userdosen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('Jenis Kelamin', 'Jenis Kelamin'), ('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], default='Jenis Kelamin', max_length=15),
        ),
    ]
