# Generated by Django 5.2.1 on 2025-06-22 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_strukturpenandatangan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StrukturPenandatangan',
        ),
    ]
