# Generated by Django 5.2.1 on 2025-06-22 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_delete_strukturpenandatangan'),
    ]

    operations = [
        migrations.AddField(
            model_name='jenislayanan',
            name='penandatangan_layanan',
            field=models.JSONField(blank=True, help_text='Konfigurasi penandatangan. Contoh: [{"urutan": 1, "jabatan": "Ketua Prodi"}, {"urutan": 2, "jabatan": "Dekan"}]', null=True),
        ),
        migrations.CreateModel(
            name='TandaTanganLayanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan_penandatangan', models.CharField(max_length=255)),
                ('urutan', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Menunggu Tanda Tangan'), ('signed', 'Sudah Ditandatangani'), ('rejected', 'Ditolak'), ('skipped', 'Dilewati')], default='pending', max_length=20)),
                ('waktu_tanda_tangan', models.DateTimeField(blank=True, null=True)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('layanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daftar_tanda_tangan', to='accounts.layanan')),
                ('user_penandatangan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanda_tangan_layanan_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tanda Tangan Layanan',
                'verbose_name_plural': 'Tanda Tangan Layanan',
                'ordering': ['layanan', 'urutan'],
            },
        ),
    ]
