# Generated by Django 5.2.1 on 2025-05-25 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('super_admin', 'SUPER ADMIN'), ('dekan_fakultas', 'USER DEKAN'), ('pejabat_jurusan', 'USER PEJABAT JURUSAN'), ('ketua_prodi', 'USER KETUA PRODI'), ('staff_fakultas', 'USER STAFF FAKULTAS'), ('staff_prodi', 'USER STAFF PRODI'), ('dosen', 'USER DOSEN'), ('mahasiswa', 'USER MAHASISWA')], default='mahasiswa', max_length=20),
        ),
        migrations.AlterField(
            model_name='fakultas',
            name='dekan',
            field=models.OneToOneField(blank=True, limit_choices_to={'user_type': 'dekan_fakultas'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fakultas_dipimpin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='programstudi',
            name='kaprodi',
            field=models.OneToOneField(blank=True, limit_choices_to={'user_type': 'ketua_prodi'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prodi_dipimpin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userdosen',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type__in': ['dosen', 'dekan_fakultas', 'ketua_prodi', 'pejabat_jurusan']}, on_delete=django.db.models.deletion.CASCADE, related_name='dosen_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprodi',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type': 'ketua_prodi'}, on_delete=django.db.models.deletion.CASCADE, related_name='staff_prodi_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PejabatJurusan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan', models.CharField(choices=[('Ketua', 'Ketua'), ('Sekretaris', 'Sekretaris')], max_length=15)),
                ('tgl_mulai', models.DateField()),
                ('tgl_selesai', models.DateField()),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('plt', models.BooleanField(blank=True, null=True)),
                ('jurusan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.jurusan')),
                ('pejabat', models.OneToOneField(blank=True, limit_choices_to={'user_type': 'pejabat_jurusan'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pejabat_jurusan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Pejabat Jurusan',
                'verbose_name_plural': 'User Pejabat Jurusan',
            },
        ),
        migrations.DeleteModel(
            name='JurusanPejabat',
        ),
    ]
