# Generated by Django 5.2.1 on 2025-05-25 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_customuser_gender_alter_customuser_user_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprodi',
            name='program_studi',
        ),
        migrations.RemoveField(
            model_name='userprodi',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='fakultas',
            options={'verbose_name': 'Nama Fakultas', 'verbose_name_plural': 'Nama Fakultas'},
        ),
        migrations.CreateModel(
            name='UserKetuaProdi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode_mulai', models.DateField()),
                ('periode_selesai', models.DateField()),
                ('program_studi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ketua_prodi_rel', to='accounts.programstudi')),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'ketua_prodi'}, on_delete=django.db.models.deletion.CASCADE, related_name='ketua_prodi_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Ketua Program Studi',
                'verbose_name_plural': 'User Ketua Program Studi',
            },
        ),
        migrations.CreateModel(
            name='UserStaffFakultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan', models.CharField(blank=True, max_length=50)),
                ('nip', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='NIP')),
                ('fakultas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='accounts.fakultas')),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'staff_fakultas'}, on_delete=django.db.models.deletion.CASCADE, related_name='staff_fakultas_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Staff Fakultas',
                'verbose_name_plural': 'User Staff Fakultas',
            },
        ),
        migrations.CreateModel(
            name='UserStaffProdi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan', models.CharField(blank=True, choices=[('admin_prodi', 'Admin Prodi'), ('sekretaris_prodi', 'Sekretaris Prodi')], max_length=50)),
                ('nip', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='NIP')),
                ('program_studi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_prodi', to='accounts.programstudi')),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'staff_prodi'}, on_delete=django.db.models.deletion.CASCADE, related_name='staff_prodi_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Staff Program Studi',
                'verbose_name_plural': 'User Staff Program Studi',
            },
        ),
        migrations.DeleteModel(
            name='UserFakultas',
        ),
        migrations.DeleteModel(
            name='UserProdi',
        ),
    ]
