# Generated by Django 5.2.1 on 2025-06-22 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_jenislayanan_penandatangan_layanan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jenislayanan',
            name='penandatangan_layanan',
        ),
        migrations.DeleteModel(
            name='TandaTanganLayanan',
        ),
    ]
