# Generated by Django 5.2.1 on 2025-06-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_jenislayanan_penandatangan_layanan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jenislayanan',
            name='penandatangan_otomatis',
            field=models.JSONField(blank=True, default=list, help_text="Daftar penandatangan otomatis dalam format JSON. Contoh: [{'role': 'Ketua Prodi', 'user_type': 'ketua_prodi', 'order': 1}]", null=True),
        ),
    ]
