# Generated by Django 5.2.1 on 2025-05-25 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_userprodi_program_studi_remove_userprodi_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userketuaprodi',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userketuaprodi',
            name='plt',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
