# Generated by Django 5.2.1 on 2025-05-26 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_userketuaprodi_label_userketuaprodi_plt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstaffprodi',
            name='jabatan',
            field=models.CharField(blank=True, choices=[('Admin Prodi', 'Admin Prodi'), ('Sekretaris Prodi', 'Sekretaris Prodi')], max_length=50),
        ),
        migrations.CreateModel(
            name='SkripsiJudul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_1', models.CharField(max_length=255)),
                ('deskripsi_1', models.TextField()),
                ('judul_2', models.CharField(max_length=255)),
                ('deskripsi_2', models.TextField()),
                ('judul_3', models.CharField(max_length=255)),
                ('deskripsi_3', models.TextField()),
                ('judul_diterima', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Menunggu Review'), ('reviewed_prodi', 'Sudah Direview Prodi'), ('reviewed_fakultas', 'Sudah Direview Fakultas'), ('accepted', 'Diterima'), ('rejected', 'Ditolak'), ('revision', 'Perlu Revisi')], default='pending', max_length=20)),
                ('tanggal_pengajuan', models.DateTimeField(auto_now_add=True)),
                ('tanggal_update', models.DateTimeField(auto_now=True)),
                ('catatan_prodi', models.TextField(blank=True, null=True)),
                ('catatan_fakultas', models.TextField(blank=True, null=True)),
                ('catatan_pembimbing', models.TextField(blank=True, null=True)),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengajuan_judul', to='accounts.usermahasiswa')),
                ('pembimbing_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bimbingan_1', to='accounts.userdosen')),
                ('pembimbing_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bimbingan_2', to='accounts.userdosen')),
            ],
            options={
                'verbose_name': 'Pengajuan Judul Skripsi',
                'verbose_name_plural': 'Pengajuan Judul Skripsi',
                'ordering': ['-tanggal_pengajuan'],
            },
        ),
    ]
