# Generated by Django 5.2.1 on 2025-05-31 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_userstaffprodi_jabatan_skripsijudul'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pejabatjurusan',
            options={'ordering': ['jurusan', 'jabatan'], 'verbose_name': 'Pejabat Jurusan', 'verbose_name_plural': 'Pejabat Jurusan'},
        ),
        migrations.AddField(
            model_name='pejabatjurusan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pejabatjurusan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pejabatjurusan',
            name='jurusan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pejabat_jurusan', to='accounts.jurusan'),
        ),
        migrations.AlterField(
            model_name='pejabatjurusan',
            name='plt',
            field=models.BooleanField(default=False, help_text='Pelaksana Tugas'),
        ),
        migrations.AddConstraint(
            model_name='pejabatjurusan',
            constraint=models.UniqueConstraint(fields=('jurusan', 'jabatan'), name='unique_jabatan_per_jurusan'),
        ),
    ]
