# Generated by Django 5.2.1 on 2025-05-31 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_pejabatjurusan_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pejabatjurusan',
            options={'verbose_name': 'User Pejabat Jurusan', 'verbose_name_plural': 'User Pejabat Jurusan'},
        ),
        migrations.RemoveConstraint(
            model_name='pejabatjurusan',
            name='unique_jabatan_per_jurusan',
        ),
        migrations.RemoveField(
            model_name='pejabatjurusan',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pejabatjurusan',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='pejabatjurusan',
            name='jurusan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.jurusan'),
        ),
        migrations.AlterField(
            model_name='pejabatjurusan',
            name='plt',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
