# Generated by Django 5.2.1 on 2025-06-22 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_layanan_nomor_surat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layanan',
            name='nomor_surat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layanan_nomor_surat', to='accounts.nomorsurat'),
        ),
    ]
